version: "3.9" #version of docker-compose
services:
  mysql:
    container_name: mysql_customerapi
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1                    #default password of the MySQL container
      - MYSQL_DATABASE=customerapi_db
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    volumes:
      #- ./data:/var/lib/mysql                         #database data volume
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
  data_api:
    container_name: customerapi_service
    build: .
    ports:
      - "8081:8080"
    expose:
      - "8081"
