version: "3.9" #version of docker-compose
services:
  mysql:
    restart: always
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1                    #default password of the MySQL container
      - MYSQL_DATABASE=customerapi_db
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    volumes:
      #- ./data:/var/lib/mysql                         #database data volume
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
  data_api:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: customerapi.Dockerfile
    ports:
      - "8081:8080"
    expose:
      - "8081"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"