version: "3.9" #version of docker-compose
services:
  mysql:
    container_name: mysql_spring_security_demo_08_jdbc_plaintext
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1                    #default password of the MySQL container
      - MYSQL_DATABASE=spring_security_demo_plaintext
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    volumes:
      #- ./data:/var/lib/mysql                         #database data volume
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
  web:
      container_name: tomcat_spring_security_demo_08_jdbc_plaintext
      build: .
      ports:
        - "127.0.0.1:8080:8080"
      expose:
        - "8080"
      volumes:
        - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:rw"