version: "3.9" #version of docker-compose
services:
  mysql-service:
    image: mysql:latest
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1                    #default password of the MySQL container
      - MYSQL_DATABASE=customer_db
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    volumes:
      #- ./data:/var/lib/mysql                         #database data volume
      - ./src/main/db:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
  data-service:
    depends_on:
      - mysql-service
    build:
      context: ./
      dockerfile: customerapi2.Dockerfile
    command:
      --publish 8081:8080
    ports:
      - "8081:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"